// <auto-generated />
using System;
using AduanasExpress.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AduanasExpress.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AduanasExpress.Domain.Entitis.Asignacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AsignadoPorId")
                        .HasColumnType("int");

                    b.Property<int>("ConductorId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("int");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AsignadoPorId");

                    b.HasIndex("ConductorId");

                    b.HasIndex("SolicitudId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Asignaciones");
                });

            modelBuilder.Entity("AduanasExpress.Domain.Entitis.Conductor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaVencLicencia")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroLicencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoLicencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Conductores");
                });

            modelBuilder.Entity("AduanasExpress.Domain.Entitis.ConsumoCombustible", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostoPorGalon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Galones")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SolicitudId")
                        .HasColumnType("int");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SolicitudId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("ConsumoCombustibles");
                });

            modelBuilder.Entity("AduanasExpress.Domain.Entitis.Mantenimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRealizada")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Kilometraje")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Taller")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Mantenimientos");
                });

            modelBuilder.Entity("AduanasExpress.Domain.Entitis.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsSistema")
                        .HasColumnType("bit");

                    b.Property<string>("Icono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Acceso total al sistema",
                            EsSistema = true,
                            IsActive = true,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Acceso parcial",
                            EsSistema = true,
                            IsActive = true,
                            Nombre = "Supervisor"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Registrar solicitudes y visualizar todo",
                            EsSistema = true,
                            IsActive = true,
                            Nombre = "Operador"
                        });
                });

            modelBuilder.Entity("AduanasExpress.Domain.Entitis.RolPermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Permitido")
                        .HasColumnType("bit");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RolId", "Modulo", "Accion")
                        .IsUnique();

                    b.ToTable("RolPermisos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Accion = "ver",
                            Modulo = "vehiculos",
                            Permitido = true,
                            RolId = 1
                        },
                        new
                        {
                            Id = 2,
                            Accion = "crear",
                            Modulo = "vehiculos",
                            Permitido = true,
                            RolId = 1
                        },
                        new
                        {
                            Id = 3,
                            Accion = "editar",
                            Modulo = "vehiculos",
                            Permitido = true,
                            RolId = 1
                        },
                        new
                        {
                            Id = 4,
                            Accion = "cancelar",
                            Modulo = "vehiculos",
                            Permitido = true,
                            RolId = 1
                        },
                        new
                        {
                            Id = 5,
                            Accion = "ver",
                            Modulo = "conductores",
                            Permitido = true,
                            RolId = 1
                        },
                        new
                        {
                            Id = 6,
                            Accion = "crear",
                            Modulo = "conductores",
                            Permitido = true,
                            RolId = 1
                        },
                        new
                        {
                            Id = 7,
                            Accion = "editar",
                            Modulo = "conductores",
                            Permitido = true,
                            RolId = 1
                        },
                        new
                        {
                            Id = 8,
                            Accion = "cancelar",
                            Modulo = "conductores",
                            Permitido = true,
                            RolId = 1
                        },
                        new
                        {
                            Id = 9,
                            Accion = "ver",
                            Modulo = "solicitudes",
                            Permitido = true,
                            RolId = 1
                        },
                        new
                        {
                            Id = 10,
                            Accion = "crear",
                            Modulo = "solicitudes",
                            Permitido = true,
                            RolId = 1
                        },
                        new
                        {
                            Id = 11,
                            Accion = "editar",
                            Modulo = "solicitudes",
                            Permitido = true,
                            RolId = 1
                        },
                        new
                        {
                            Id = 12,
                            Accion = "cancelar",
                            Modulo = "solicitudes",
                            Permitido = true,
                            RolId = 1
                        },
                        new
                        {
                            Id = 13,
                            Accion = "ver",
                            Modulo = "asignaciones",
                            Permitido = true,
                            RolId = 1
                        },
                        new
                        {
                            Id = 14,
                            Accion = "asignar",
                            Modulo = "asignaciones",
                            Permitido = true,
                            RolId = 1
                        },
                        new
                        {
                            Id = 15,
                            Accion = "editar",
                            Modulo = "asignaciones",
                            Permitido = true,
                            RolId = 1
                        },
                        new
                        {
                            Id = 16,
                            Accion = "cancelar",
                            Modulo = "asignaciones",
                            Permitido = true,
                            RolId = 1
                        },
                        new
                        {
                            Id = 17,
                            Accion = "ver",
                            Modulo = "reportes",
                            Permitido = true,
                            RolId = 1
                        },
                        new
                        {
                            Id = 18,
                            Accion = "exportar",
                            Modulo = "reportes",
                            Permitido = true,
                            RolId = 1
                        },
                        new
                        {
                            Id = 19,
                            Accion = "estadisticas",
                            Modulo = "reportes",
                            Permitido = true,
                            RolId = 1
                        },
                        new
                        {
                            Id = 20,
                            Accion = "ver",
                            Modulo = "usuarios",
                            Permitido = true,
                            RolId = 1
                        },
                        new
                        {
                            Id = 21,
                            Accion = "crear",
                            Modulo = "usuarios",
                            Permitido = true,
                            RolId = 1
                        },
                        new
                        {
                            Id = 22,
                            Accion = "editar",
                            Modulo = "usuarios",
                            Permitido = true,
                            RolId = 1
                        },
                        new
                        {
                            Id = 23,
                            Accion = "cancelar",
                            Modulo = "usuarios",
                            Permitido = true,
                            RolId = 1
                        },
                        new
                        {
                            Id = 24,
                            Accion = "ver",
                            Modulo = "vehiculos",
                            Permitido = true,
                            RolId = 2
                        },
                        new
                        {
                            Id = 25,
                            Accion = "crear",
                            Modulo = "vehiculos",
                            Permitido = false,
                            RolId = 2
                        },
                        new
                        {
                            Id = 26,
                            Accion = "editar",
                            Modulo = "vehiculos",
                            Permitido = true,
                            RolId = 2
                        },
                        new
                        {
                            Id = 27,
                            Accion = "cancelar",
                            Modulo = "vehiculos",
                            Permitido = false,
                            RolId = 2
                        },
                        new
                        {
                            Id = 28,
                            Accion = "ver",
                            Modulo = "conductores",
                            Permitido = true,
                            RolId = 2
                        },
                        new
                        {
                            Id = 29,
                            Accion = "crear",
                            Modulo = "conductores",
                            Permitido = true,
                            RolId = 2
                        },
                        new
                        {
                            Id = 30,
                            Accion = "editar",
                            Modulo = "conductores",
                            Permitido = true,
                            RolId = 2
                        },
                        new
                        {
                            Id = 31,
                            Accion = "cancelar",
                            Modulo = "conductores",
                            Permitido = false,
                            RolId = 2
                        },
                        new
                        {
                            Id = 32,
                            Accion = "ver",
                            Modulo = "solicitudes",
                            Permitido = true,
                            RolId = 2
                        },
                        new
                        {
                            Id = 33,
                            Accion = "crear",
                            Modulo = "solicitudes",
                            Permitido = true,
                            RolId = 2
                        },
                        new
                        {
                            Id = 34,
                            Accion = "editar",
                            Modulo = "solicitudes",
                            Permitido = true,
                            RolId = 2
                        },
                        new
                        {
                            Id = 35,
                            Accion = "cancelar",
                            Modulo = "solicitudes",
                            Permitido = false,
                            RolId = 2
                        },
                        new
                        {
                            Id = 36,
                            Accion = "ver",
                            Modulo = "asignaciones",
                            Permitido = true,
                            RolId = 2
                        },
                        new
                        {
                            Id = 37,
                            Accion = "asignar",
                            Modulo = "asignaciones",
                            Permitido = true,
                            RolId = 2
                        },
                        new
                        {
                            Id = 38,
                            Accion = "editar",
                            Modulo = "asignaciones",
                            Permitido = true,
                            RolId = 2
                        },
                        new
                        {
                            Id = 39,
                            Accion = "cancelar",
                            Modulo = "asignaciones",
                            Permitido = false,
                            RolId = 2
                        },
                        new
                        {
                            Id = 40,
                            Accion = "ver",
                            Modulo = "reportes",
                            Permitido = true,
                            RolId = 2
                        },
                        new
                        {
                            Id = 41,
                            Accion = "exportar",
                            Modulo = "reportes",
                            Permitido = true,
                            RolId = 2
                        },
                        new
                        {
                            Id = 42,
                            Accion = "estadisticas",
                            Modulo = "reportes",
                            Permitido = false,
                            RolId = 2
                        },
                        new
                        {
                            Id = 43,
                            Accion = "ver",
                            Modulo = "usuarios",
                            Permitido = true,
                            RolId = 2
                        },
                        new
                        {
                            Id = 44,
                            Accion = "crear",
                            Modulo = "usuarios",
                            Permitido = false,
                            RolId = 2
                        },
                        new
                        {
                            Id = 45,
                            Accion = "editar",
                            Modulo = "usuarios",
                            Permitido = false,
                            RolId = 2
                        },
                        new
                        {
                            Id = 46,
                            Accion = "cancelar",
                            Modulo = "usuarios",
                            Permitido = false,
                            RolId = 2
                        },
                        new
                        {
                            Id = 47,
                            Accion = "ver",
                            Modulo = "vehiculos",
                            Permitido = true,
                            RolId = 3
                        },
                        new
                        {
                            Id = 48,
                            Accion = "crear",
                            Modulo = "vehiculos",
                            Permitido = false,
                            RolId = 3
                        },
                        new
                        {
                            Id = 49,
                            Accion = "editar",
                            Modulo = "vehiculos",
                            Permitido = false,
                            RolId = 3
                        },
                        new
                        {
                            Id = 50,
                            Accion = "cancelar",
                            Modulo = "vehiculos",
                            Permitido = false,
                            RolId = 3
                        },
                        new
                        {
                            Id = 51,
                            Accion = "ver",
                            Modulo = "conductores",
                            Permitido = true,
                            RolId = 3
                        },
                        new
                        {
                            Id = 52,
                            Accion = "crear",
                            Modulo = "conductores",
                            Permitido = false,
                            RolId = 3
                        },
                        new
                        {
                            Id = 53,
                            Accion = "editar",
                            Modulo = "conductores",
                            Permitido = false,
                            RolId = 3
                        },
                        new
                        {
                            Id = 54,
                            Accion = "cancelar",
                            Modulo = "conductores",
                            Permitido = false,
                            RolId = 3
                        },
                        new
                        {
                            Id = 55,
                            Accion = "ver",
                            Modulo = "solicitudes",
                            Permitido = true,
                            RolId = 3
                        },
                        new
                        {
                            Id = 56,
                            Accion = "crear",
                            Modulo = "solicitudes",
                            Permitido = true,
                            RolId = 3
                        },
                        new
                        {
                            Id = 57,
                            Accion = "editar",
                            Modulo = "solicitudes",
                            Permitido = false,
                            RolId = 3
                        },
                        new
                        {
                            Id = 58,
                            Accion = "cancelar",
                            Modulo = "solicitudes",
                            Permitido = false,
                            RolId = 3
                        },
                        new
                        {
                            Id = 59,
                            Accion = "ver",
                            Modulo = "asignaciones",
                            Permitido = true,
                            RolId = 3
                        },
                        new
                        {
                            Id = 60,
                            Accion = "asignar",
                            Modulo = "asignaciones",
                            Permitido = false,
                            RolId = 3
                        },
                        new
                        {
                            Id = 61,
                            Accion = "editar",
                            Modulo = "asignaciones",
                            Permitido = false,
                            RolId = 3
                        },
                        new
                        {
                            Id = 62,
                            Accion = "cancelar",
                            Modulo = "asignaciones",
                            Permitido = false,
                            RolId = 3
                        },
                        new
                        {
                            Id = 63,
                            Accion = "ver",
                            Modulo = "reportes",
                            Permitido = true,
                            RolId = 3
                        },
                        new
                        {
                            Id = 64,
                            Accion = "exportar",
                            Modulo = "reportes",
                            Permitido = false,
                            RolId = 3
                        },
                        new
                        {
                            Id = 65,
                            Accion = "estadisticas",
                            Modulo = "reportes",
                            Permitido = false,
                            RolId = 3
                        },
                        new
                        {
                            Id = 66,
                            Accion = "ver",
                            Modulo = "usuarios",
                            Permitido = true,
                            RolId = 3
                        },
                        new
                        {
                            Id = 67,
                            Accion = "crear",
                            Modulo = "usuarios",
                            Permitido = false,
                            RolId = 3
                        },
                        new
                        {
                            Id = 68,
                            Accion = "editar",
                            Modulo = "usuarios",
                            Permitido = false,
                            RolId = 3
                        },
                        new
                        {
                            Id = 69,
                            Accion = "cancelar",
                            Modulo = "usuarios",
                            Permitido = false,
                            RolId = 3
                        });
                });

            modelBuilder.Entity("AduanasExpress.Domain.Entitis.SolicitudTransporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaSolicitante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CantidadColaboradores")
                        .HasColumnType("int");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaViaje")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HoraSalida")
                        .HasColumnType("time");

                    b.Property<string>("MotivoViaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PuntoOrigen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoViaje")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioSolicitaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioSolicitaId");

                    b.ToTable("SolicitudesTransporte");
                });

            modelBuilder.Entity("AduanasExpress.Domain.Entitis.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("Rol");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AduanasExpress.Domain.Entitis.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Año")
                        .HasColumnType("int");

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaUltimoMant")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Kilometraje")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("AduanasExpress.Domain.Entitis.Asignacion", b =>
                {
                    b.HasOne("AduanasExpress.Domain.Entitis.Usuario", "AsignadoPor")
                        .WithMany()
                        .HasForeignKey("AsignadoPorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AduanasExpress.Domain.Entitis.Conductor", "Conductor")
                        .WithMany()
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AduanasExpress.Domain.Entitis.SolicitudTransporte", "Solicitud")
                        .WithMany()
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AduanasExpress.Domain.Entitis.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AsignadoPor");

                    b.Navigation("Conductor");

                    b.Navigation("Solicitud");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("AduanasExpress.Domain.Entitis.Conductor", b =>
                {
                    b.HasOne("AduanasExpress.Domain.Entitis.Usuario", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("AduanasExpress.Domain.Entitis.ConsumoCombustible", b =>
                {
                    b.HasOne("AduanasExpress.Domain.Entitis.SolicitudTransporte", "Solicitud")
                        .WithMany()
                        .HasForeignKey("SolicitudId");

                    b.HasOne("AduanasExpress.Domain.Entitis.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("AduanasExpress.Domain.Entitis.Mantenimiento", b =>
                {
                    b.HasOne("AduanasExpress.Domain.Entitis.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("AduanasExpress.Domain.Entitis.RolPermiso", b =>
                {
                    b.HasOne("AduanasExpress.Domain.Entitis.Rol", "Rol")
                        .WithMany("Permisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AduanasExpress.Domain.Entitis.SolicitudTransporte", b =>
                {
                    b.HasOne("AduanasExpress.Domain.Entitis.Usuario", "UsuarioSolicita")
                        .WithMany()
                        .HasForeignKey("UsuarioSolicitaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UsuarioSolicita");
                });

            modelBuilder.Entity("AduanasExpress.Domain.Entitis.Usuario", b =>
                {
                    b.HasOne("AduanasExpress.Domain.Entitis.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AduanasExpress.Domain.Entitis.Rol", b =>
                {
                    b.Navigation("Permisos");
                });
#pragma warning restore 612, 618
        }
    }
}
